In [2]:
# import libraries
import pandas as pd
import yfinance as yf
import numpy as np

In [4]:
# ['XOM','CVX','JNJ','PEP','MRK','COP','MDT','VZ','O','GIS']
# define tickers
tickers = ['XOM','CVX','JNJ','PEP','MRK','COP','MDT','VZ','O','GIS']
# download the data
start_date = "2014-01-01"
end_date = "2025-12-31"
stocks = yf.download(tickers, start=start_date, end=end_date,actions=True, group_by='ticker')
stocks.head()

[*********************100%***********************]  10 of 10 completed

Ticker            GIS                                                      \
Price            Open       High        Low      Close   Volume Dividends
Date
2014-01-02  31.247439  31.297839  31.039544  31.121443  2205500      0.00
2014-01-03  31.127752  31.222251  30.932455  31.033253  2309700      0.00
2014-01-06  31.108853  31.247449  30.919856  31.083652  3260200      0.00
2014-01-07  31.272652  31.461648  31.033256  31.404949  4606800      0.00
2014-01-08  31.322415  31.373200  30.725678  30.833597  5747800      0.38

Ticker                          VZ                        ...       JNJ  \
Price      Stock Splits       Open       High        Low  ...    Volume
Date                                                      ...
2014-01-02          0.0  25.312497  25.389856  25.245450  ...   5919600
2014-01-03          0.0  25.441440  25.441440  24.868968  ...   5637600
2014-01-06          0.0  25.152624  25.307346  24.858653  ...   7443500
2014-01-07          0.0  25.333131  25.477540  25.054633  ...  11063300
2014-01-08          0.0  25.384257  25.582368  25.212214  ...   9096700

Ticker                                   XOM                                   \
Price      Dividends Stock Splits       Open       High        Low      Close
Date
2014-01-02       0.0          0.0  60.221164  60.316945  59.496834  59.712337
2014-01-03       0.0          0.0  59.724322  59.963770  59.347193  59.568684
2014-01-06       0.0          0.0  59.826075  59.945798  59.197523  59.658463
2014-01-07       0.0          0.0  59.628514  60.592293  59.514775  60.502499
2014-01-08       0.0          0.0  60.574351  60.574351  59.951786  60.304970

Ticker
Price         Volume Dividends Stock Splits
Date
2014-01-02  11028100       0.0          0.0
2014-01-03   9295600       0.0          0.0
2014-01-06  11848500       0.0          0.0
2014-01-07  11187000       0.0          0.0
2014-01-08  11180400       0.0          0.0

[5 rows x 70 columns]

In [74]:
stocks.columns

MultiIndex([('MDT',         'Open'),
            ('MDT',         'High'),
            ('MDT',          'Low'),
            ('MDT',        'Close'),
            ('MDT',       'Volume'),
            ('MDT',    'Dividends'),
            ('MDT', 'Stock Splits'),
            ('GIS',         'Open'),
            ('GIS',         'High'),
            ('GIS',          'Low'),
            ('GIS',        'Close'),
            ('GIS',       'Volume'),
            ('GIS',    'Dividends'),
            ('GIS', 'Stock Splits'),
            ('MRK',         'Open'),
            ('MRK',         'High'),
            ('MRK',          'Low'),
            ('MRK',        'Close'),
            ('MRK',       'Volume'),
            ('MRK',    'Dividends'),
            ('MRK', 'Stock Splits'),
            ('JNJ',         'Open'),
            ('JNJ',         'High'),
            ('JNJ',          'Low'),
            ('JNJ',        'Close'),
            ('JNJ',       'Volume'),
            ('JNJ',    'Dividends'),
            ('JNJ', 'Stock Splits'),
            ('XOM',         'Open'),
            ('XOM',         'High'),
            ('XOM',          'Low'),
            ('XOM',        'Close'),
            ('XOM',       'Volume'),
            ('XOM',    'Dividends'),
            ('XOM', 'Stock Splits'),
            ('COP',         'Open'),
            ('COP',         'High'),
            ('COP',          'Low'),
            ('COP',        'Close'),
            ('COP',       'Volume'),
            ('COP',    'Dividends'),
            ('COP', 'Stock Splits'),
            ('CVX',         'Open'),
            ('CVX',         'High'),
            ('CVX',          'Low'),
            ('CVX',        'Close'),
            ('CVX',       'Volume'),
            ('CVX',    'Dividends'),
            ('CVX', 'Stock Splits'),
            ( 'VZ',         'Open'),
            ( 'VZ',         'High'),
            ( 'VZ',          'Low'),
            ( 'VZ',        'Close'),
            ( 'VZ',       'Volume'),
            ( 'VZ',    'Dividends'),
            ( 'VZ', 'Stock Splits'),
            (  'O',         'Open'),
            (  'O',         'High'),
            (  'O',          'Low'),
            (  'O',        'Close'),
            (  'O',       'Volume'),
            (  'O',    'Dividends'),
            (  'O', 'Stock Splits'),
            ('PEP',         'Open'),
            ('PEP',         'High'),
            ('PEP',          'Low'),
            ('PEP',        'Close'),
            ('PEP',       'Volume'),
            ('PEP',    'Dividends'),
            ('PEP', 'Stock Splits')],
           names=['Ticker', 'Price'])

In [75]:
# drop all the null values in stocks DataFrame
stocks = stocks.dropna(how='all')
stocks

Ticker            MDT                                                       \
Price            Open       High        Low      Close    Volume Dividends
Date
2014-01-02  42.004347  42.187900  41.879532  42.026375   4219000      0.00
2014-01-03  42.731237  42.951500  42.371471  42.834026  12577400      0.00
2014-01-06  43.428738  43.883950  43.245185  43.480133  10538100      0.00
2014-01-07  43.891302  44.148279  43.707749  43.935356   6510600      0.00
2014-01-08  43.950038  44.735646  43.861933  44.669567   6725000      0.00
...               ...        ...        ...        ...       ...       ...
2025-12-23  95.155780  95.526603  94.921569  95.116745   3579700      0.00
2025-12-24  95.058189  95.243597  94.658084  94.921562   1979000      0.00
2025-12-26  95.069026  95.108349  94.380907  94.882248   4340500      0.71
2025-12-29  95.098517  95.265638  94.331753  94.518532   4790600      0.00
2025-12-30  94.685640  95.236135  94.449714  95.019875   3741200      0.00

Ticker                         GIS                        ...        O  \
Price      Stock Splits       Open       High        Low  ...   Volume
Date                                                      ...
2014-01-02          0.0  31.247448  31.297848  31.039553  ...  1684327
2014-01-03          0.0  31.127748  31.222247  30.932451  ...  1269876
2014-01-06          0.0  31.108849  31.247445  30.919853  ...  1957291
2014-01-07          0.0  31.272641  31.461637  31.033244  ...  2088768
2014-01-08          0.0  31.322427  31.373212  30.725689  ...  1867610
...                 ...        ...        ...        ...  ...      ...
2025-12-23          0.0  45.136034  45.145568  44.278118  ...  6825100
2025-12-24          0.0  44.611749  44.840529  44.449700  ...  2415500
2025-12-26          0.0  44.754737  45.069305  44.630814  ...  4445800
2025-12-29          0.0  45.031176  45.097903  44.649878  ...  6390400
2025-12-30          0.0  44.754734  45.002575  44.459227  ...  4993700

Ticker                                    PEP                          \
Price      Dividends Stock Splits        Open        High         Low
Date
2014-01-02       0.0          0.0   56.844785   56.885911   56.083929
2014-01-03       0.0          0.0   56.289541   56.803632   56.289541
2014-01-06       0.0          0.0   56.344405   56.625444   56.262153
2014-01-07       0.0          0.0   56.632272   57.571342   56.625416
2014-01-08       0.0          0.0   57.118945   57.317727   56.762505
...              ...          ...         ...         ...         ...
2025-12-23       0.0          0.0  144.367741  144.367741  140.807339
2025-12-24       0.0          0.0  141.032916  141.229093  140.209026
2025-12-26       0.0          0.0  140.807319  141.180037  140.346330
2025-12-29       0.0          0.0  140.983876  142.268755  140.846561
2025-12-30       0.0          0.0  141.209469  142.484545  141.160425

Ticker
Price            Close   Volume Dividends Stock Splits
Date
2014-01-02   56.275856  3275900       0.0          0.0
2014-01-03   56.371792  3287200       0.0          0.0
2014-01-06   56.399242  3888400       0.0          0.0
2014-01-07   57.221764  6332400       0.0          0.0
2014-01-08   57.057251  5653300       0.0          0.0
...                ...      ...       ...          ...
2025-12-23  140.925034  7254800       0.0          0.0
2025-12-24  140.983887  2618700       0.0          0.0
2025-12-26  141.023102  4975500       0.0          0.0
2025-12-29  141.474289  7201900       0.0          0.0
2025-12-30  141.395828  4713800       0.0          0.0

[3017 rows x 70 columns]

KeyError: 'Date'

In [39]:
# make a seperate dataset for revenue,netincome and totaldebt
ticker_statements = []
for y in tickers:
    tickery = yf.Ticker(y)
    revenue = tickery.financials.loc['Total Revenue']
    if revenue is not None and not revenue.empty:
        revenue = revenue.reset_index()
        revenue.columns = ["Date", "Revenue"]
        revenue["Ticker"] = y
        ticker_statements.append(revenue)
    netincome = tickery.financials.loc['Net Income']
    if netincome is not None and not netincome.empty:
        netincome = netincome.reset_index()
        netincome.columns = ["Date", "NetIncome"]
        netincome["Ticker"] = y
        ticker_statements.append(netincome)
    totaldebt = tickery.balance_sheet.loc['Total Debt']
    if totaldebt is not None and not totaldebt.empty:
        totaldebt = totaldebt.reset_index()
        totaldebt.columns = ["Date", "TotalDebt"]
        totaldebt["Ticker"] = y
        ticker_statements.append(totaldebt)
# print("revenue:", revenue)
# print("netincome:", netincome)
# print("totaldebt:", totaldebt)
print(ticker_statements)

[        Date       Revenue Ticker
0 2025-12-31  3.239050e+11    XOM
1 2024-12-31  3.392470e+11    XOM
2 2023-12-31  3.346970e+11    XOM
3 2022-12-31  3.986750e+11    XOM
4 2021-12-31           NaN    XOM,         Date     NetIncome Ticker
0 2025-12-31  2.884400e+10    XOM
1 2024-12-31  3.368000e+10    XOM
2 2023-12-31  3.601000e+10    XOM
3 2022-12-31  5.574000e+10    XOM
4 2021-12-31           NaN    XOM,         Date     TotalDebt Ticker
0 2025-12-31           NaN    XOM
1 2024-12-31  4.171000e+10    XOM
2 2023-12-31  4.157300e+10    XOM
3 2022-12-31  4.119300e+10    XOM
4 2021-12-31  4.770400e+10    XOM,         Date       Revenue Ticker
0 2025-12-31  1.844320e+11    CVX
1 2024-12-31  1.934140e+11    CVX
2 2023-12-31  1.969130e+11    CVX
3 2022-12-31  2.357170e+11    CVX,         Date     NetIncome Ticker
0 2025-12-31  1.229900e+10    CVX
1 2024-12-31  1.766100e+10    CVX
2 2023-12-31  2.136900e+10    CVX
3 2022-12-31  3.546500e+10    CVX,         Date     TotalDebt Ticker
0 2025-12-31  4.075800e+10    CVX
1 2024-12-31  2.454100e+10    CVX
2 2023-12-31  2.083600e+10    CVX
3 2022-12-31  2.333900e+10    CVX
4 2021-12-31           NaN    CVX,         Date       Revenue Ticker
0 2025-12-31  9.419300e+10    JNJ
1 2024-12-31  8.882100e+10    JNJ
2 2023-12-31  8.515900e+10    JNJ
3 2022-12-31  7.999000e+10    JNJ
4 2021-12-31           NaN    JNJ,         Date     NetIncome Ticker
0 2025-12-31  2.680400e+10    JNJ
1 2024-12-31  1.406600e+10    JNJ
2 2023-12-31  3.515300e+10    JNJ
3 2022-12-31  1.794100e+10    JNJ
4 2021-12-31           NaN    JNJ,         Date     TotalDebt Ticker
0 2025-12-31  4.793300e+10    JNJ
1 2024-12-31  3.663400e+10    JNJ
2 2023-12-31  2.933200e+10    JNJ
3 2022-12-31  3.964200e+10    JNJ
4 2021-12-31           NaN    JNJ,         Date       Revenue Ticker
0 2025-12-31  9.392500e+10    PEP
1 2024-12-31  9.185400e+10    PEP
2 2023-12-31  9.147100e+10    PEP
3 2022-12-31  8.639200e+10    PEP
4 2021-12-31           NaN    PEP,         Date     NetIncome Ticker
0 2025-12-31  8.240000e+09    PEP
1 2024-12-31  9.578000e+09    PEP
2 2023-12-31  9.074000e+09    PEP
3 2022-12-31  8.910000e+09    PEP
4 2021-12-31           NaN    PEP,         Date     TotalDebt Ticker
0 2025-12-31  4.990100e+10    PEP
1 2024-12-31  4.494800e+10    PEP
2 2023-12-31  4.466100e+10    PEP
3 2022-12-31  3.955400e+10    PEP
4 2021-12-31           NaN    PEP,         Date       Revenue Ticker
0 2025-12-31  6.501100e+10    MRK
1 2024-12-31  6.416800e+10    MRK
2 2023-12-31  6.011500e+10    MRK
3 2022-12-31  5.928300e+10    MRK
4 2021-12-31           NaN    MRK,         Date     NetIncome Ticker
0 2025-12-31  1.825400e+10    MRK
1 2024-12-31  1.711700e+10    MRK
2 2023-12-31  3.650000e+08    MRK
3 2022-12-31  1.451900e+10    MRK
4 2021-12-31           NaN    MRK,         Date     TotalDebt Ticker
0 2025-12-31  4.933900e+10    MRK
1 2024-12-31  3.711100e+10    MRK
2 2023-12-31  3.505500e+10    MRK
3 2022-12-31  3.069100e+10    MRK
4 2021-12-31           NaN    MRK,         Date       Revenue Ticker
0 2025-12-31  5.894400e+10    COP
1 2024-12-31  5.474500e+10    COP
2 2023-12-31  5.614100e+10    COP
3 2022-12-31  7.849400e+10    COP
4 2021-12-31           NaN    COP,         Date     NetIncome Ticker
0 2025-12-31  7.988000e+09    COP
1 2024-12-31  9.245000e+09    COP
2 2023-12-31  1.095700e+10    COP
3 2022-12-31  1.868000e+10    COP
4 2021-12-31           NaN    COP,         Date     TotalDebt Ticker
0 2025-12-31  2.344400e+10    COP
1 2024-12-31  2.432400e+10    COP
2 2023-12-31  1.893700e+10    COP
3 2022-12-31  1.664300e+10    COP
4 2021-12-31           NaN    COP,         Date       Revenue Ticker
0 2026-04-30  3.636400e+10    MDT
1 2025-04-30  3.353700e+10    MDT
2 2024-04-30  3.236400e+10    MDT
3 2023-04-30  3.122700e+10    MDT
4 2022-04-30           NaN    MDT,         Date     NetIncome Ticker
0 2026-04-30  4.801000e+09    MDT
1 2025-04-30  4.662000e+09    MDT
2 2024-04-30  3.676000e+09    MDT
3 2023-04-30  3.758000e+09    MDT
4 2022-04-30           NaN    MDT,         Date     TotalDebt Ticker
0 2026-04-30  2.796100e+10    MDT
1 2025-04-30  2.851600e+10    MDT
2 2024-04-30  2.502400e+10    MDT
3 2023-04-30  2.436400e+10    MDT
4 2022-04-30           NaN    MDT,         Date       Revenue Ticker
0 2025-12-31  1.381910e+11     VZ
1 2024-12-31  1.347880e+11     VZ
2 2023-12-31  1.339740e+11     VZ
3 2022-12-31  1.368350e+11     VZ
4 2021-12-31           NaN     VZ,         Date     NetIncome Ticker
0 2025-12-31  1.717400e+10     VZ
1 2024-12-31  1.750600e+10     VZ
2 2023-12-31  1.161400e+10     VZ
3 2022-12-31  2.125600e+10     VZ
4 2021-12-31           NaN     VZ,         Date     TotalDebt Ticker
0 2025-12-31  1.816430e+11     VZ
1 2024-12-31  1.683570e+11     VZ
2 2023-12-31  1.749420e+11     VZ
3 2022-12-31  1.763310e+11     VZ
4 2021-12-31           NaN     VZ,         Date       Revenue Ticker
0 2025-12-31  5.749377e+09      O
1 2024-12-31  5.271142e+09      O
2 2023-12-31  4.078993e+09      O
3 2022-12-31  3.343681e+09      O
4 2021-12-31           NaN      O,         Date     NetIncome Ticker
0 2025-12-31  1.058590e+09      O
1 2024-12-31  8.607720e+08      O
2 2023-12-31  8.723090e+08      O
3 2022-12-31  8.694080e+08      O
4 2021-12-31           NaN      O,         Date     TotalDebt Ticker
0 2025-12-31  2.934585e+10      O
1 2024-12-31  2.675714e+10      O
2 2023-12-31  2.198970e+10      O
3 2022-12-31  1.860030e+10      O
4 2021-12-31           NaN      O,         Date       Revenue Ticker
0 2026-05-31  1.842460e+10    GIS
1 2025-05-31  1.948660e+10    GIS
2 2024-05-31  1.985720e+10    GIS
3 2023-05-31  2.009420e+10    GIS,         Date     NetIncome Ticker
0 2026-05-31 -8.760000e+07    GIS
1 2025-05-31  2.295200e+09    GIS
2 2024-05-31  2.496600e+09    GIS
3 2023-05-31  2.593900e+09    GIS,         Date     TotalDebt Ticker
0 2026-05-31  1.394040e+10    GIS
1 2025-05-31  1.529670e+10    GIS
2 2024-05-31  1.331510e+10    GIS
3 2023-05-31  1.206480e+10    GIS
4 2022-05-31           NaN    GIS]

In [40]:
# make a single dataframe for the fiancial statements
financials_df = pd.concat(ticker_statements, axis=0)
# # make sure the Date column is in datetime format
# financials_df['Date'] = pd.to_datetime(financials_df['Date'])
print(financials_df)

         Date       Revenue Ticker  NetIncome     TotalDebt
0  2025-12-31  3.239050e+11    XOM        NaN           NaN
1  2024-12-31  3.392470e+11    XOM        NaN           NaN
2  2023-12-31  3.346970e+11    XOM        NaN           NaN
3  2022-12-31  3.986750e+11    XOM        NaN           NaN
4  2021-12-31           NaN    XOM        NaN           NaN
..        ...           ...    ...        ...           ...
0  2026-05-31           NaN    GIS        NaN  1.394040e+10
1  2025-05-31           NaN    GIS        NaN  1.529670e+10
2  2024-05-31           NaN    GIS        NaN  1.331510e+10
3  2023-05-31           NaN    GIS        NaN  1.206480e+10
4  2022-05-31           NaN    GIS        NaN           NaN

[146 rows x 5 columns]

In [41]:
#reset index of combined_statements and stocks DataFrames
stocks2 = (stocks.stack(level=0).rename_axis(['Date', 'Ticker']).reset_index())
financials_df2 = financials_df.reset_index()

C:\Users\DataAnalyticsCoding\AppData\Local\Temp\ipykernel_10412\1639051369.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stocks2 = (stocks.stack(level=0).rename_axis(['Date', 'Ticker']).reset_index())

In [42]:
# check index levels of both DataFrames
fdflevel = financials_df2.index.nlevels
slevel = stocks2.index.nlevels
print(fdflevel, slevel)

1 1

In [45]:
stocks2['Date'] = pd.to_datetime(stocks2['Date'])
financials_df2['Date'] = pd.to_datetime(financials_df2['Date'])

stock_data = pd.merge(stocks2,
                      financials_df2,
                      how='left',
                      on=["Ticker", "Date"])
stock_data

,Date,Ticker,Open,High,Low,Close,Volume,Dividends,Stock Splits,index,Revenue,NetIncome,TotalDebt
0,2014-01-02,COP,46.698438,47.130401,46.206667,46.372807,4351800,0.0,0.0,NaN,NaN,NaN,NaN
1,2014-01-02,CVX,73.546258,73.794444,73.103065,73.357162,4540300,0.0,0.0,NaN,NaN,NaN,NaN
2,2014-01-02,GIS,31.247439,31.297839,31.039544,31.121443,2205500,0.0,0.0,NaN,NaN,NaN,NaN
3,2014-01-02,JNJ,64.577231,64.995279,64.485122,64.499290,5919600,0.0,0.0,NaN,NaN,NaN,NaN
4,2014-01-02,MDT,42.004358,42.187911,41.879543,42.026386,4219000,0.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30203,2025-12-30,MRK,105.188857,105.336685,104.114593,104.528526,6497900,0.0,0.0,NaN,NaN,NaN,NaN
30204,2025-12-30,O,54.976401,55.121255,54.783263,55.072968,4993700,0.0,0.0,NaN,NaN,NaN,NaN
30205,2025-12-30,PEP,141.209469,142.484545,141.160425,141.395828,4713800,0.0,0.0,NaN,NaN,NaN,NaN
30206,2025-12-30,VZ,38.543013,38.819137,38.485883,38.752487,15581300,0.0,0.0,NaN,NaN,NaN,NaN
30207,2025-12-30,XOM,119.487152,120.177834,119.023410,119.378616,11150500,0.0,0.0,NaN,NaN,NaN,NaN

In [46]:
# save the datadframe to a CSV file
dividends_sustainability = stock_data.to_csv("dividends_sustainability_data.csv", index=False)